### ISSUE TITLE
Question about MeliusNet paper

### ISSUE THREAD

**Issue by iamhankai** [hpi-xnor/BMXNet-v2#10]
I have noticed that you have just released your new paper: MeliusNet: Can Binary Neural Networks Achieve MobileNet-level Accuracy? Congratulations for the great job.

In your paper, you said MeliusNet for the first time can match the accuracy (**69.2%** and **70.7%**) of the popular compact network MobileNet in terms of model size and accuracy. 

Our paper [AutoBNN](http://openaccess.thecvf.com/content_ICCVW_2019/papers/NeurArch/Shen_Searching_for_Accurate_Binary_Neural_Architectures_ICCVW_2019_paper.pdf) [1] already achieved **69.65%** top1 accuracy with our binary neural networks. We also released our code: https://github.com/LaVieEnRoseSMZ/AutoBNN. You can check it and cite our paper to improve the quality of your paper :)

[1] Shen, Mingzhu, et al. "Searching for accurate binary neural architectures." Proceedings of the IEEE International Conference on Computer Vision Workshops. 2019.

**Comment by Jopyth** [comment]
Hi,

thank you for your kind words. I read your paper and think it is a very interesting approach, so I did cite it in the related work section. However, when I read your paper and compared the number of FLOPs of your models to those of MobileNet I did not see that you achieved MobileNet level accuracy.

I might be mistaken, but from what I can see your models can not be directly compared to MobileNet, since they either need more FLOPs or achieve lower accuracy, depending on which models we compare. From what your wrote in your paper I understood, that Res18-Auto-A needs 495 M instead of the 569 M operations of MobileNet 1.0, but has 2 % lower accuracy. Compared to MobileNet 0.75 (68.4% with 325M FLOPs) you achieve a slightly better accuracy, but need 50 % more FLOPs. Similarly the accuracy of Res18-Auto-B is between MobileNet 0.75 and 1.0, but it needs more FLOPs than both MobileNet versions. Is there something I missed? Also did you measure or calculate the model size of Res18-Auto-A and B for ImageNet? (I opened an issue about this at your repository.)

But you are definitely right our wording should be improved, since we only considered BNNs that have a similar model size **and** a similar number of operations.

Best regards
Joseph

**Comment by iamhankai** [comment]
Hi Joseph,

Thanks for your reply. You're right that Res18-Auto-B is larger than MobileNet, but it can achieve the performance of MobileNet with sightly higher FLOPs. I think it's yet a big step towards binary neural networks with high accuracy.

Your work is convincing and inspires us that binary neural networks can also achieve high accuracy with fewer memory computation cost over MobileNet. Thank you.

Best,
Kai
