### ISSUE TITLE
QDense inference

### ISSUE THREAD

**Issue by pnicotera** [hpi-xnor/BMXNet-v2#2]
@Jopyth 
Greetings, and thank you for the BMXNet library.

The QDense and QConv classes' hybrid_forward methods may set the offset to the number of weights, as follows (https://github.com/hpi-xnor/BMXNet-v2/blob/master/python/mxnet/gluon/nn/binary_layers.py):

    self._offset = reduce(mul, weight.shape[1:], 1)

When using binary inputs, weights, and activations, and no bias, adding this offset seems to make the range of possible output values between zero and the number of weights (i.e., zero when all x*w contributions are "-1", and the number of weights when all contributions are "+1").  This is given the output computed as:

    h = (h + self._offset) / 2

    h_min = (-count(w) + count(w)) / 2 = 0

    h_max = (count(w) + count(w)) / 2 = count(w)

Thus, it seems that applying a subsequent binary QActivation (i.e., det_sign) to the output of a binary QDense or non-scaled binary QConv layer will always yield "+1", never "-1".  Is this the intended behavior, or do I misunderstand it?

Thanks very much for any insight!

**Comment by Jopyth** [comment]
You are completely correct, that is why we use BatchNorm layers between binary layers to normalize the values with a mean of zero and both negative and positive values ([Example](https://github.com/hpi-xnor/BMXNet-v2-examples/blob/46b36d7340c9270541cf1f03206a927ece1645a2/binary_models/resnet.py#L76-L80).)
However you can also set `no_offset=True` otherwise, but so far only for QConv (see [here](https://github.com/hpi-xnor/BMXNet-v2/blob/master/python/mxnet/gluon/nn/binary_layers.py#L185))
This would disable the corresponding scaling.

**Comment by pnicotera** [comment]
I see!  Thanks very much for the clear explanation and examples.  Best of luck with future developments!
